#!/usr/bin/env bash

set -eo pipefail

GIT_ROOT=$(cd "${BASH_SOURCE%/*}" && git rev-parse --show-toplevel)

cd "${GIT_ROOT}"

trash "${RELEASE_FILE}" >/dev/null 2>&1 || true
trash "${PLUGIN_NAMESPACE}.streamDeckPlugin" >/dev/null 2>&1 || true
streamdeck pack "${SOURCE_DIR}"
mv -f "${PLUGIN_NAMESPACE}.streamDeckPlugin" "${RELEASE_FILE}"

cd -
